server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    client_max_body_size 100m;
    sendfile on;
    tcp_nopush on;
    aio threads;
    directio 8m;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_pass app:9000;
        fastcgi_read_timeout 300;
    }

    location /_protected_media/ {
        internal;
        alias /srv/courses/;
        try_files $uri =404;

        add_header Accept-Ranges bytes always;
        add_header Cache-Control "private, max-age=86400" always;
        expires 1d;
    }
}
